In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('Data/dataset_mood_smartphone.csv',index_col=0)
data

              id                     time        variable    value
1        AS14.01  2014-02-26 13:00:00.000            mood    6.000
2        AS14.01  2014-02-26 15:00:00.000            mood    6.000
3        AS14.01  2014-02-26 18:00:00.000            mood    6.000
4        AS14.01  2014-02-26 21:00:00.000            mood    7.000
5        AS14.01  2014-02-27 09:00:00.000            mood    6.000
6        AS14.01  2014-02-27 12:00:00.000            mood    6.000
7        AS14.01  2014-02-27 15:00:00.000            mood    7.000
8        AS14.01  2014-03-21 09:00:00.000            mood    6.000
9        AS14.01  2014-03-21 11:00:00.000            mood    6.000
10       AS14.01  2014-03-21 15:00:00.000            mood    7.000
11       AS14.01  2014-03-21 19:00:00.000            mood    6.000
12       AS14.01  2014-03-21 21:00:00.000            mood    6.000
13       AS14.01  2014-03-22 08:00:00.000            mood    7.000
14       AS14.01  2014-03-22 12:00:00.000            mood    7.000
15       AS14.01  2014-03-22 15:00:00.000            mood    7.000
16       AS14.01  2014-03-22 18:00:00.000            mood    6.000
17       AS14.01  2014-03-22 21:00:00.000            mood    5.000
18       AS14.01  2014-03-23 10:00:00.000            mood    7.000
19       AS14.01  2014-03-23 12:00:00.000            mood    7.000
20       AS14.01  2014-03-23 15:00:00.000            mood    8.000
21       AS14.01  2014-03-23 19:00:00.000            mood    6.000
22       AS14.01  2014-03-23 21:00:00.000            mood    6.000
23       AS14.01  2014-03-24 09:00:00.000            mood    6.000
24       AS14.01  2014-03-24 12:00:00.000            mood    6.000
25       AS14.01  2014-03-24 15:00:00.000            mood    6.000
26       AS14.01  2014-03-24 18:00:00.000            mood    5.000
27       AS14.01  2014-03-24 21:00:00.000            mood    7.000
28       AS14.01  2014-03-25 09:00:00.000            mood    6.000
29       AS14.01  2014-03-25 15:00:00.000            mood    7.000
30       AS14.01  2014-03-25 20:00:00.000            mood    8.000
...          ...                      ...             ...      ...
2749463  AS14.28  2014-04-27 10:44:59.062  appCat.weather    1.009
2749481  AS14.28  2014-04-27 10:48:48.413  appCat.weather    9.035
2749546  AS14.28  2014-04-27 12:46:35.697  appCat.weather   24.278
2749602  AS14.28  2014-04-27 13:52:35.108  appCat.weather   15.076
2749608  AS14.28  2014-04-27 13:53:17.608  appCat.weather   39.993
2750181  AS14.28  2014-05-01 20:38:50.595  appCat.weather   40.242
2751060  AS14.28  2014-05-03 21:18:04.157  appCat.weather   43.930
2751227  AS14.28  2014-05-04 08:38:49.355  appCat.weather   12.122
2751229  AS14.28  2014-05-04 08:39:02.530  appCat.weather   17.962
2751518  AS14.28  2014-05-05 06:06:32.828  appCat.weather   11.059
2751730  AS14.28  2014-05-05 20:09:54.138  appCat.weather   42.411
2752088  AS14.28  2014-05-06 20:20:31.098  appCat.weather   31.711
2752310  AS14.28  2014-05-07 13:45:27.233  appCat.weather    1.119
2752401  AS14.28  2014-05-07 16:45:40.653  appCat.weather    8.067
2764945  AS14.30  2014-03-23 08:46:30.237  appCat.weather  344.863
2764968  AS14.30  2014-03-23 12:16:04.568  appCat.weather   22.074
2765154  AS14.30  2014-03-24 08:35:37.507  appCat.weather   15.070
2765807  AS14.30  2014-03-26 08:50:33.236  appCat.weather    6.087
2767251  AS14.30  2014-03-30 13:15:37.865  appCat.weather    1.007
2769195  AS14.30  2014-04-06 10:57:54.450  appCat.weather   51.507
2769196  AS14.30  2014-04-06 11:24:23.055  appCat.weather   41.881
2769197  AS14.30  2014-04-06 11:38:32.033  appCat.weather    4.117
2769509  AS14.30  2014-04-07 18:13:31.111  appCat.weather   11.039
2769513  AS14.30  2014-04-07 18:16:49.107  appCat.weather   60.829
2769514  AS14.30  2014-04-07 18:21:04.197  appCat.weather    3.018
2770399  AS14.30  2014-04-11 07:51:16.948  appCat.weather    8.032
2772465  AS14.30  2014-04-19 11:00:32.747  appCat.weather    3.008
2774026  AS14.30  2014-04-26 10:19:07.434  appCat.weather    7.026
2774133  AS14.30  2014-04-27 00:44:48.450  appCat.weather   23.033
2784435  AS14.32  2014-04-07 18:25:14.036  appCat.weather   22.431

[376912 rows x 4 columns]

In [4]:
# split up time into multiple columns
data[['date','timeOfDay']] = data.time.str.split(" ",expand=True,)
data[['year','month','day']] = data.date.str.split("-",expand=True,)

In [5]:
# create data structure that helps determine day of week

# 2014 dates
# February (sat 1 - fri 28)
# March (sat 1 - mon 31)
# April (tues 1 - wed 30)
# May (thurs 1 - sat 31)
# June (sun 1 - mon 30)

# mon,tues,wed,thurs,fri,sat,sun = 1,2,3,4,5,6,7

# key is month
# value is [weekday of first day, length of month]
calendar = {
    '02' : [6,28], 
    '03' : [6,31],
    '04' : [2,30], 
    '05' : [4,31], 
    '06' : [7,30], 
}

days = {}
for key,value in calendar.items():
    weekdays = []
    counter = value[0]
    for day in range(value[1]):
        mod = counter % 7
        if mod == 0:
            weekdays.append(7)
        else:
            weekdays.append(mod)
        counter += 1
    days[key] = weekdays

print("")
for k,v in days.items():
    print(k,v)

02 [6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5]
03 [6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1]
04 [2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3]
05 [4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6]
06 [7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1]

In [6]:
# add column for day of week

weekday = []
for index, row in data.iterrows():
    weekday.append(days[row.month][int(row.day)-1])

data['weekday'] = weekday
data

KeyboardInterrupt:

In [22]:
# add column for phase of the day

# Morning (5 AM to 12 PM)
# Afternoon (12 PM to 5 PM)
# Evening (5 PM to 10 PM)
# Night (10 PM to 5 AM)

# morning,afternoon,evening,night = 1,2,3,4

phaseOfDay = []
for index, row in data.iterrows():
    time = int(row.timeOfDay.split(':')[0])
    if time > 5 and time < 12:
        phaseOfDay.append(1)
    elif time > 12 and time < 17:
        phaseOfDay.append(2)
    elif time > 17 and time < 22:
        phaseOfDay.append(3)
    else:
        phaseOfDay.append(4)

data['phaseOfDay'] = phaseOfDay
data

,id,time,variable,value,date,timeOfDay,year,month,day,weekday,phaseOfDay
1,AS14.01,2014-02-26 13:00:00.000,mood,6.000,2014-02-26,13:00:00.000,2014,02,26,3,2
2,AS14.01,2014-02-26 15:00:00.000,mood,6.000,2014-02-26,15:00:00.000,2014,02,26,3,2
3,AS14.01,2014-02-26 18:00:00.000,mood,6.000,2014-02-26,18:00:00.000,2014,02,26,3,3
4,AS14.01,2014-02-26 21:00:00.000,mood,7.000,2014-02-26,21:00:00.000,2014,02,26,3,3
5,AS14.01,2014-02-27 09:00:00.000,mood,6.000,2014-02-27,09:00:00.000,2014,02,27,4,1
6,AS14.01,2014-02-27 12:00:00.000,mood,6.000,2014-02-27,12:00:00.000,2014,02,27,4,4
7,AS14.01,2014-02-27 15:00:00.000,mood,7.000,2014-02-27,15:00:00.000,2014,02,27,4,2
8,AS14.01,2014-03-21 09:00:00.000,mood,6.000,2014-03-21,09:00:00.000,2014,03,21,5,1
9,AS14.01,2014-03-21 11:00:00.000,mood,6.000,2014-03-21,11:00:00.000,2014,03,21,5,1
10,AS14.01,2014-03-21 15:00:00.000,mood,7.000,2014-03-21,15:00:00.000,2014,03,21,5,2
11,AS14.01,2014-03-21 19:00:00.000,mood,6.000,2014-03-21,19:00:00.000,2014,03,21,5,3
12,AS14.01,2014-03-21 21:00:00.000,mood,6.000,2014-03-21,21:00:00.000,2014,03,21,5,3
13,AS14.01,2014-03-22 08:00:00.000,mood,7.000,2014-03-22,08:00:00.000,2014,03,22,6,1
14,AS14.01,2014-03-22 12:00:00.000,mood,7.000,2014-03-22,12:00:00.000,2014,03,22,6,4
15,AS14.01,2014-03-22 15:00:00.000,mood,7.000,2014-03-22,15:00:00.000,2014,03,22,6,2
16,AS14.01,2014-03-22 18:00:00.000,mood,6.000,2014-03-22,18:00:00.000,2014,03,22,6,3
17,AS14.01,2014-03-22 21:00:00.000,mood,5.000,2014-03-22,21:00:00.000,2014,03,22,6,3
18,AS14.01,2014-03-23 10:00:00.000,mood,7.000,2014-03-23,10:00:00.000,2014,03,23,7,1
19,AS14.01,2014-03-23 12:00:00.000,mood,7.000,2014-03-23,12:00:00.000,2014,03,23,7,4
20,AS14.01,2014-03-23 15:00:00.000,mood,8.000,2014-03-23,15:00:00.000,2014,03,23,7,2
21,AS14.01,2014-03-23 19:00:00.000,mood,6.000,2014-03-23,19:00:00.000,2014,03,23,7,3
22,AS14.01,2014-03-23 21:00:00.000,mood,6.000,2014-03-23,21:00:00.000,2014,03,23,7,3
23,AS14.01,2014-03-24 09:00:00.000,mood,6.000,2014-03-24,09:00:00.000,2014,03,24,1,1
24,AS14.01,2014-03-24 12:00:00.000,mood,6.000,2014-03-24,12:00:00.000,2014,03,24,1,4
25,AS14.01,2014-03-24 15:00:00.000,mood,6.000,2014-03-24,15:00:00.000,2014,03,24,1,2
26,AS14.01,2014-03-24 18:00:00.000,mood,5.000,2014-03-24,18:00:00.000,2014,03,24,1,3
27,AS14.01,2014-03-24 21:00:00.000,mood,7.000,2014-03-24,21:00:00.000,2014,03,24,1,3
28,AS14.01,2014-03-25 09:00:00.000,mood,6.000,2014-03-25,09:00:00.000,2014,03,25,2,1
29,AS14.01,2014-03-25 15:00:00.000,mood,7.000,2014-03-25,15:00:00.000,2014,03,25,2,2
30,AS14.01,2014-03-25 20:00:00.000,mood,8.000,2014-03-25,20:00:00.000,2014,03,25,2,3
...,...,...,...,...,...,...,...,...,...,...,...
2749463,AS14.28,2014-04-27 10:44:59.062,appCat.weather,1.009,2014-04-27,10:44:59.062,2014,04,27,7,1
2749481,AS14.28,2014-04-27 10:48:48.413,appCat.weather,9.035,2014-04-27,10:48:48.413,2014,04,27,7,1
2749546,AS14.28,2014-04-27 12:46:35.697,appCat.weather,24.278,2014-04-27,12:46:35.697,2014,04,27,7,4
2749602,AS14.28,2014-04-27 13:52:35.108,appCat.weather,15.076,2014-04-27,13:52:35.108,2014,04,27,7,2
2749608,AS14.28,2014-04-27 13:53:17.608,appCat.weather,39.993,2014-04-27,13:53:17.608,2014,04,27,7,2
2750181,AS14.28,2014-05-01 20:38:50.595,appCat.weather,40.242,2014-05-01,20:38:50.595,2014,05,01,4,3
2751060,AS14.28,2014-05-03 21:18:04.157,appCat.weather,43.930,2014-05-03,21:18:04.157,2014,05,03,6,3
2751227,AS14.28,2014-05-04 08:38:49.355,appCat.weather,12.122,2014-05-04,08:38:49.355,2014,05,04,7,1
2751229,AS14.28,2014-05-04 08:39:02.530,appCat.weather,17.962,2014-05-04,08:39:02.530,2014,05,04,7,1
2751518,AS14.28,2014-05-05 06:06:32.828,appCat.weather,11.059,2014-05-05,06:06:32.828,2014,05,05,1,1
2751730,AS14.28,2014-05-05 20:09:54.138,appCat.weather,42.411,2014-05-05,20:09:54.138,2014,05,05,1,3
2752088,AS14.28,2014-05-06 20:20:31.098,appCat.weather,31.711,2014-05-06,20:20:31.098,2014,05,06,2,3
2752310,AS14.28,2014-05-07 13:45:27.233,appCat.weather,1.119,2014-05-07,13:45:27.233,2014,05,07,3,2
2752401,AS14.28,2014-05-07 16:45:40.653,appCat.weather,8.067,2014-05-07,16:45:40.653,2014,05,07,3,2
2764945,AS14.30,2014-03-23 08:46:30.237,appCat.weather,344.863,2014-03-23,08:46:30.237,2014,03,23,7,1
2764968,AS14.30,2014-03-23 12:16:04.568,appCat.weather,22.074,2014-03-23,12:16:04.568,2014,03,23,7,4
2765154,AS14.30,2014-03-24 08:35:37.507,appCat.weather,15.070,2014-03-24,08:35:37.507,2014,03,24,1,1
2765807,AS14.30,2014-03-26 08:50:33.236,appCat.weather,6.087,2014-03-26,08:50:33.236,2014,03,26,3,1
2767251,AS14.30,2014-03-30 13:15:37.865,appCat.weather,1.007,2014-03-30,13:15:37.865,2014,03,30,7,2
2769195,AS14.30,2014-04-06 10:57:54.450,appCat.weather,51.507,2014-04-06,10:57:54.450,2014,04,06,7,1
2769196,AS14.30,2014-04-06 11:24:23.055,appCat.weather,41.881,2014-04-06,11:24:23.055,2014,04,06,7,1
2769197,AS14.30,2014-04-06 11:38:32.033,appCat.weather,4.117,2014-04-06,11:38:32.033,2014,04,06,7,1
2769509,AS14.30,2014-04-07 18:13:31.111,appCat.weather,11.039,2014-04-07,18:13:31.111,2014,04,07,1,3
2769513,AS14.30,2014-04-07 18:16:49.107,appCat.weather,60.829,2014-04-07,18:16:49.107,2014,04,07,1,3
2769514,AS14.30,2014-04-07 18:21:04.197,appCat.weather,3.018,2014-04-07,18:21:04.197,2014,04,07,1,3
2770399,AS14.30,2014-04-11 07:51:16.948,appCat.weather,8.032,2014-04-11,07:51:16.948,2014,04,11,5,1
2772465,AS14.30,2014-04-19 11:00:32.747,appCat.weather,3.008,2014-04-19,11:00:32.747,2014,04,19,6,1
2774026,AS14.30,2014-04-26 10:19:07.434,appCat.weather,7.026,2014-04-26,10:19:07.434,2014,04,26,6,1
2774133,AS14.30,2014-04-27 00:44:48.450,appCat.weather,23.033,2014-04-27,00:44:48.450,2014,04,27,7,4
2784435,AS14.32,2014-04-07 18:25:14.036,appCat.weather,22.431,2014-04-07,18:25:14.036,2014,04,07,1,3

In [23]:
print(data.size)
data.head()

4146032

,id,time,variable,value,date,timeOfDay,year,month,day,weekday,phaseOfDay
1,AS14.01,2014-02-26 13:00:00.000,mood,6.0,2014-02-26,13:00:00.000,2014,02,26,3,2
2,AS14.01,2014-02-26 15:00:00.000,mood,6.0,2014-02-26,15:00:00.000,2014,02,26,3,2
3,AS14.01,2014-02-26 18:00:00.000,mood,6.0,2014-02-26,18:00:00.000,2014,02,26,3,3
4,AS14.01,2014-02-26 21:00:00.000,mood,7.0,2014-02-26,21:00:00.000,2014,02,26,3,3
5,AS14.01,2014-02-27 09:00:00.000,mood,6.0,2014-02-27,09:00:00.000,2014,02,27,4,1

In [26]:
data.to_csv(r'Data\data_with_new_features.csv',index=True)